const Types = {
  DATA_SECCESS: "DATA_SECCESS",
  DATA_FAIL: "DATA_FAIL",
  GETUSER_TRUE : "GETUSER_TRUE",
  GETUSER_FALSE : "GETUSER_FALSE",
  LOADING_TRUE : "LOADING_TRUE",
  LOADING_FALSE :"LOADING_FALSE",
  FILTER_USER:"FILTER_USER"
};

export { Types };
